import xmltodict
import json

# Parses key to lowercase strings (more conventional for mongo) and parses int values as int (when applicable)
def postprocessor(path, key, value):
    try:
        return key.lower(), int(value)
    except (ValueError, TypeError):
        return key.lower(), value

# Parser when seeing municipalities with one facility parses it as object and not array of object. Same goes for facilities with one activity. This fixes that
def parse_one_item_arrays(m_dict):
    for d in m_dict['data']['district']:
        for m in d['municipalities']:
            if 'facilities' in m:
                if type(m['facilities']) is not list:
                    m['facilities'] = [m['facilities']]
                for f in m['facilities']:
                    if 'activities' in f:
                        if type(f['activities']) is not list:
                            f['activities'] = [f['activities']]
    return m_dict

MY_XML_HERE = """<?xml version="1.0" encoding="iso-8859-1" ?>
<DATA>
<DISTRICT>
<_ID>3</_ID>
<DESIGNATION>Braga</DESIGNATION>
<REGION>
<COD>1</COD>
<DESIGNATION>Norte</DESIGNATION>
</REGION>
<MUNICIPALITIES>
<COD>301</COD>
<DESIGNATION>Amares</DESIGNATION>
<REGION>
<COD>1</COD>
<DESIGNATION>Norte</DESIGNATION>
</REGION>
</MUNICIPALITIES>
<MUNICIPALITIES>
<COD>302</COD>
<DESIGNATION>Barcelos</DESIGNATION>
<REGION>
<COD>1</COD>
<DESIGNATION>Norte</DESIGNATION>
</REGION>
<FACILITIES>
<ID>17</ID>
<NAME>AUDITÓRIO DA BIBLIOTECA DA C. M. DE BARCELOS</NAME>
<CAPACITY>110</CAPACITY>
<ROOMTYPE>Auditório</ROOMTYPE>
<ADDRESS>LARGO DOUTOR JOSÉ NOVAIS</ADDRESS>
<ACTIVITY>cinema</ACTIVITY>
<ACTIVITY>música</ACTIVITY>
<ACTIVITY>teatro</ACTIVITY>
</FACILITIES>
<FACILITIES>
<ID>18</ID>
<NAME>SALA DE ESPECTÁCULOS DO CENTRO CÍVICO DOS FEITOS</NAME>
<CAPACITY>130</CAPACITY>
<ROOMTYPE>Outras salas de espetáculo</ROOMTYPE>
<ADDRESS>LUG DO MONTE - FEITOS</ADDRESS>
<ACTIVITY>dança</ACTIVITY>
<ACTIVITY>música</ACTIVITY>
<ACTIVITY>teatro</ACTIVITY>
</FACILITIES>
<FACILITIES>
<ID>16</ID>
<NAME>TEATRO GIL VICENTE</NAME>
<CAPACITY>196</CAPACITY>
<ROOMTYPE>Cine-Teatro</ROOMTYPE>
<ADDRESS>LARGO DR. MARTINS LIMA</ADDRESS>
<ACTIVITY>cinema</ACTIVITY>
<ACTIVITY>música</ACTIVITY>
<ACTIVITY>teatro</ACTIVITY>
</FACILITIES>
<FACILITIES>
<ID>19</ID>
<NAME>CINEMA CINEMAX - SALA 1</NAME>
<CAPACITY>214</CAPACITY>
<ROOMTYPE>Cinema</ROOMTYPE>
<ADDRESS>CAMPO 25 ABRIL</ADDRESS>
<ACTIVITY>cinema</ACTIVITY>
</FACILITIES>
<FACILITIES>
<ID>20</ID>
<NAME>CINEMA CINEMAX - SALA 2</NAME>
<CAPACITY>211</CAPACITY>
<ROOMTYPE>Cinema</ROOMTYPE>
<ADDRESS>CAMPO 25 ABRIL</ADDRESS>
<ACTIVITY>cinema</ACTIVITY>
</FACILITIES>
</MUNICIPALITIES>
<MUNICIPALITIES>
<COD>303</COD>
<DESIGNATION>Braga</DESIGNATION>
<REGION>
<COD>1</COD>
<DESIGNATION>Norte</DESIGNATION>
</REGION>
<FACILITIES>
<ID>21</ID>
<NAME>SALA PRINCIPAL DO TEATRO CIRCO DE BRAGA</NAME>
<CAPACITY>897</CAPACITY>
<ROOMTYPE>Auditório</ROOMTYPE>
<ADDRESS>AV DA LIBERDADE 785</ADDRESS>
<ACTIVITY>dança</ACTIVITY>
<ACTIVITY>música</ACTIVITY>
<ACTIVITY>teatro</ACTIVITY>
</FACILITIES>
<FACILITIES>
<ID>22</ID>
<NAME>PEQUENO AUDITÓRIO TEATRO CIRCO DE BRAGA</NAME>
<CAPACITY>240</CAPACITY>
<ROOMTYPE>Auditório</ROOMTYPE>
<ADDRESS>AV DA LIBERDADE 785</ADDRESS>
<ACTIVITY>cinema</ACTIVITY>
<ACTIVITY>música</ACTIVITY>
<ACTIVITY>teatro</ACTIVITY>
</FACILITIES>
<FACILITIES>
<ID>23</ID>
<NAME>CINEMA CINEMAX - SALA 1</NAME>
<CAPACITY>181</CAPACITY>
<ROOMTYPE>Cinema</ROOMTYPE>
<ADDRESS>CENTRO COMERCIAL BRAGASHOPPING</ADDRESS>
<ACTIVITY>cinema</ACTIVITY>
</FACILITIES>
<FACILITIES>
<ID>24</ID>
<NAME>CINEMA CINEMAX - SALA 2</NAME>
<CAPACITY>219</CAPACITY>
<ROOMTYPE>Cinema</ROOMTYPE>
<ADDRESS>CENTRO COMERCIAL BRAGASHOPPING</ADDRESS>
<ACTIVITY>cinema</ACTIVITY>
</FACILITIES>
<FACILITIES>
<ID>25</ID>
<NAME>CINEMA CINEMAX - SALA 3</NAME>
<CAPACITY>157</CAPACITY>
<ROOMTYPE>Cinema</ROOMTYPE>
<ADDRESS>CENTRO COMERCIAL BRAGASHOPPING</ADDRESS>
<ACTIVITY>cinema</ACTIVITY>
</FACILITIES>
<FACILITIES>
<ID>26</ID>
<NAME>CINEMA CINEMAX - SALA 4</NAME>
<CAPACITY>157</CAPACITY>
<ROOMTYPE>Cinema</ROOMTYPE>
<ADDRESS>CENTRO COMERCIAL BRAGASHOPPING</ADDRESS>
<ACTIVITY>cinema</ACTIVITY>
</FACILITIES>
<FACILITIES>
<ID>27</ID>
<NAME>CINEMA CINEMAX - SALA 5</NAME>
<CAPACITY>157</CAPACITY>
<ROOMTYPE>Cinema</ROOMTYPE>
<ADDRESS>CENTRO COMERCIAL BRAGASHOPPING</ADDRESS>
<ACTIVITY>cinema</ACTIVITY>
</FACILITIES>
<FACILITIES>
<ID>28</ID>
<NAME>CINEMA BRAGA PARQUE - SALA 1</NAME>
<CAPACITY>112</CAPACITY>
<ROOMTYPE>Cinema</ROOMTYPE>
<ADDRESS>CENTRO COMERCIAL BRAGA PARQUE-QTA DOS CONGREGADOS</ADDRESS>
<ACTIVITY>cinema</ACTIVITY>
</FACILITIES>
<FACILITIES>
<ID>29</ID>
<NAME>CINEMA BRAGA PARQUE - SALA 2</NAME>
<CAPACITY>189</CAPACITY>
<ROOMTYPE>Cinema</ROOMTYPE>
<ADDRESS>CENTRO COMERCIAL BRAGA PARQUE-QTA DOS CONGREGADOS</ADDRESS>
<ACTIVITY>cinema</ACTIVITY>
</FACILITIES>
<FACILITIES>
<ID>30</ID>
<NAME>CINEMA BRAGA PARQUE - SALA 3</NAME>
<CAPACITY>383</CAPACITY>
<ROOMTYPE>Cinema</ROOMTYPE>
<ADDRESS>CENTRO COMERCIAL BRAGA PARQUE-QTA DOS CONGREGADOS</ADDRESS>
<ACTIVITY>cinema</ACTIVITY>
</FACILITIES>
<FACILITIES>
<ID>31</ID>
<NAME>CINEMA BRAGA PARQUE - SALA 4</NAME>
<CAPACITY>187</CAPACITY>
<ROOMTYPE>Cinema</ROOMTYPE>
<ADDRESS>CENTRO COMERCIAL BRAGA PARQUE-QTA DOS CONGREGADOS</ADDRESS>
<ACTIVITY>cinema</ACTIVITY>
</FACILITIES>
<FACILITIES>
<ID>32</ID>
<NAME>CINEMA BRAGA PARQUE - SALA 5</NAME>
<CAPACITY>224</CAPACITY>
<ROOMTYPE>Cinema</ROOMTYPE>
<ADDRESS>CENTRO COMERCIAL BRAGA PARQUE-QTA DOS CONGREGADOS</ADDRESS>
<ACTIVITY>cinema</ACTIVITY>
</FACILITIES>
<FACILITIES>
<ID>33</ID>
<NAME>CINEMA BRAGA PARQUE - SALA 6</NAME>
<CAPACITY>224</CAPACITY>
<ROOMTYPE>Cinema</ROOMTYPE>
<ADDRESS>CENTRO COMERCIAL BRAGA PARQUE-QTA DOS CONGREGADOS</ADDRESS>
<ACTIVITY>cinema</ACTIVITY>
</FACILITIES>
<FACILITIES>
<ID>34</ID>
<NAME>CINEMA BRAGA PARQUE - SALA 7</NAME>
<CAPACITY>183</CAPACITY>
<ROOMTYPE>Cinema</ROOMTYPE>
<ADDRESS>CENTRO COMERCIAL BRAGA PARQUE-QTA DOS CONGREGADOS</ADDRESS>
<ACTIVITY>cinema</ACTIVITY>
</FACILITIES>
<FACILITIES>
<ID>35</ID>
<NAME>CINEMA BRAGA PARQUE - SALA 8</NAME>
<CAPACITY>151</CAPACITY>
<ROOMTYPE>Cinema</ROOMTYPE>
<ADDRESS>CENTRO COMERCIAL BRAGA PARQUE-QTA DOS CONGREGADOS</ADDRESS>
<ACTIVITY>cinema</ACTIVITY>
</FACILITIES>
<FACILITIES>
<ID>36</ID>
<NAME>CINEMA BRAGA PARQUE - SALA 9</NAME>
<CAPACITY>171</CAPACITY>
<ROOMTYPE>Cinema</ROOMTYPE>
<ADDRESS>CENTRO COMERCIAL BRAGA PARQUE-QTA DOS CONGREGADOS</ADDRESS>
<ACTIVITY>cinema</ACTIVITY>
</FACILITIES>
</MUNICIPALITIES>
<MUNICIPALITIES>
<COD>304</COD>
<DESIGNATION>Cabeceiras de Basto</DESIGNATION>
<REGION>
<COD>1</COD>
<DESIGNATION>Norte</DESIGNATION>
</REGION>
</MUNICIPALITIES>
<MUNICIPALITIES>
<COD>305</COD>
<DESIGNATION>Celorico de Basto</DESIGNATION>
<REGION>
<COD>1</COD>
<DESIGNATION>Norte</DESIGNATION>
</REGION>
</MUNICIPALITIES>
<MUNICIPALITIES>
<COD>306</COD>
<DESIGNATION>Esposende</DESIGNATION>
<REGION>
<COD>1</COD>
<DESIGNATION>Norte</DESIGNATION>
</REGION>
<FACILITIES>
<ID>37</ID>
<NAME>AUDITÓRIO MUNICIPAL DE ESPOSENDE</NAME>
<CAPACITY>50</CAPACITY>
<ROOMTYPE>Auditório</ROOMTYPE>
<ADDRESS>LG RODRIGUES SAMPAIO</ADDRESS>
<ACTIVITY>cinema</ACTIVITY>
<ACTIVITY>música</ACTIVITY>
</FACILITIES>
</MUNICIPALITIES>
<MUNICIPALITIES>
<COD>307</COD>
<DESIGNATION>Fafe</DESIGNATION>
<REGION>
<COD>1</COD>
<DESIGNATION>Norte</DESIGNATION>
</REGION>
<FACILITIES>
<ID>40</ID>
<NAME>PAVILHÃO MULTIUSOS DE FAFE</NAME>
<CAPACITY>3300</CAPACITY>
<ROOMTYPE>Recinto multiusos</ROOMTYPE>
<ADDRESS>PARQUE DA CIDADE</ADDRESS>
<ACTIVITY>dança</ACTIVITY>
<ACTIVITY>música</ACTIVITY>
<ACTIVITY>teatro</ACTIVITY>
</FACILITIES>
<FACILITIES>
<ID>39</ID>
<NAME>SALA PRINCIPAL DO CINE TEATRO DE FAFE</NAME>
<CAPACITY>302</CAPACITY>
<ROOMTYPE>Cine-Teatro</ROOMTYPE>
<ADDRESS>RUA MONSENHOR VIEIRA DE CASTRO</ADDRESS>
<ACTIVITY>dança</ACTIVITY>
<ACTIVITY>música</ACTIVITY>
<ACTIVITY>teatro</ACTIVITY>
</FACILITIES>
<FACILITIES>
<ID>41</ID>
<NAME>SALA MANOEL DE OLIVEIRA CINE TEATRO FAFE</NAME>
<CAPACITY>152</CAPACITY>
<ROOMTYPE>Cinema</ROOMTYPE>
<ADDRESS>RUA MONSENHOR VIEIRA DE CASTRO</ADDRESS>
<ACTIVITY>cinema</ACTIVITY>
</FACILITIES>
</MUNICIPALITIES>
<MUNICIPALITIES>
<COD>308</COD>
<DESIGNATION>Guimarães</DESIGNATION>
<REGION>
<COD>1</COD>
<DESIGNATION>Norte</DESIGNATION>
</REGION>
<FACILITIES>
<ID>43</ID>
<NAME>CAFÉ CONCERTO DO CENTRO DE ARTES E ESPECTÁCULOS</NAME>
<CAPACITY>60</CAPACITY>
<ROOMTYPE>Café concerto</ROOMTYPE>
<ADDRESS>RUA DR. JOSÉ SAMPAIO, Nº. 17 A 25</ADDRESS>
<ACTIVITY>música</ACTIVITY>
</FACILITIES>
<FACILITIES>
<ID>42</ID>
<NAME>SÃO MAMEDE CENTRO DE ARTES E ESPECTÁCULOS</NAME>
<CAPACITY>672</CAPACITY>
<ROOMTYPE>Auditório</ROOMTYPE>
<ADDRESS>R DR JOSÉ SAMPAIO</ADDRESS>
<ACTIVITY>cinema</ACTIVITY>
<ACTIVITY>dança</ACTIVITY>
<ACTIVITY>música</ACTIVITY>
<ACTIVITY>teatro</ACTIVITY>
</FACILITIES>
<FACILITIES>
<ID>44</ID>
<NAME>GRANDE AUDITÓRIO DO CENTRO CULTURAL DE VILA FLOR</NAME>
<CAPACITY>799</CAPACITY>
<ROOMTYPE>Auditório</ROOMTYPE>
<ADDRESS>AVENIDA DOM AFONSO HENRIQUES</ADDRESS>
<ACTIVITY>cinema</ACTIVITY>
<ACTIVITY>dança</ACTIVITY>
<ACTIVITY>música</ACTIVITY>
<ACTIVITY>teatro</ACTIVITY>
</FACILITIES>
<FACILITIES>
<ID>45</ID>
<NAME>PEQUENO AUDITÓRIO DO CENTRO CULTURAL DE VILA FLOR</NAME>
<CAPACITY>190</CAPACITY>
<ROOMTYPE>Auditório</ROOMTYPE>
<ADDRESS>AVENIDA DOM AFONSO HENRIQUES</ADDRESS>
<ACTIVITY>cinema</ACTIVITY>
<ACTIVITY>dança</ACTIVITY>
<ACTIVITY>música</ACTIVITY>
<ACTIVITY>teatro</ACTIVITY>
</FACILITIES>
<FACILITIES>
<ID>46</ID>
<NAME>PAVILHÃO MULTIUSOS DE GUIMARÃES</NAME>
<CAPACITY>7000</CAPACITY>
<ROOMTYPE>Recinto multiusos</ROOMTYPE>
<ADDRESS>ALAMEDA CIDADE DE LISBOA</ADDRESS>
<ACTIVITY>dança</ACTIVITY>
<ACTIVITY>música</ACTIVITY>
<ACTIVITY>teatro</ACTIVITY>
</FACILITIES>
<FACILITIES>
<ID>47</ID>
<NAME>CINEMA GUIMARÃES SHOPPING CENTER - SALA 1</NAME>
<CAPACITY>98</CAPACITY>
<ROOMTYPE>Cinema</ROOMTYPE>
<ADDRESS>LAMEIRAS - CREIXOMIL</ADDRESS>
<ACTIVITY>cinema</ACTIVITY>
</FACILITIES>
<FACILITIES>
<ID>48</ID>
<NAME>CINEMA GUIMARÃES SHOPPING CENTER - SALA 2</NAME>
<CAPACITY>274</CAPACITY>
<ROOMTYPE>Cinema</ROOMTYPE>
<ADDRESS>LAMEIRAS - CREIXOMIL</ADDRESS>
<ACTIVITY>cinema</ACTIVITY>
</FACILITIES>
<FACILITIES>
<ID>49</ID>
<NAME>CINEMA GUIMARÃES SHOPPING CENTER - SALA 3</NAME>
<CAPACITY>223</CAPACITY>
<ROOMTYPE>Cinema</ROOMTYPE>
<ADDRESS>LAMEIRAS - CREIXOMIL</ADDRESS>
<ACTIVITY>cinema</ACTIVITY>
</FACILITIES>
<FACILITIES>
<ID>50</ID>
<NAME>CINEMA GUIMARÃES SHOPPING CENTER - SALA 4</NAME>
<CAPACITY>155</CAPACITY>
<ROOMTYPE>Cinema</ROOMTYPE>
<ADDRESS>LAMEIRAS - CREIXOMIL</ADDRESS>
<ACTIVITY>cinema</ACTIVITY>
</FACILITIES>
<FACILITIES>
<ID>51</ID>
<NAME>CINEMA GUIMARÃES SHOPPING CENTER - SALA 5</NAME>
<CAPACITY>99</CAPACITY>
<ROOMTYPE>Cinema</ROOMTYPE>
<ADDRESS>LAMEIRAS - CREIXOMIL</ADDRESS>
<ACTIVITY>cinema</ACTIVITY>
</FACILITIES>
<FACILITIES>
<ID>52</ID>
<NAME>CINEMA GUIMARÃES SHOPPING CENTER - SALA 6</NAME>
<CAPACITY>131</CAPACITY>
<ROOMTYPE>Cinema</ROOMTYPE>
<ADDRESS>LAMEIRAS - CREIXOMIL</ADDRESS>
<ACTIVITY>cinema</ACTIVITY>
</FACILITIES>
<FACILITIES>
<ID>53</ID>
<NAME>CINEMAS ESPAÇO GUIMARÃES - SALA 1</NAME>
<CAPACITY>190</CAPACITY>
<ROOMTYPE>Cinema</ROOMTYPE>
<ADDRESS>ESPAÇO GUIMARÃES - RUA 25 DE ABRIL - SILVARES</ADDRESS>
<ACTIVITY>cinema</ACTIVITY>
</FACILITIES>
<FACILITIES>
<ID>54</ID>
<NAME>CINEMAS ESPAÇO GUIMARÃES - SALA 2</NAME>
<CAPACITY>150</CAPACITY>
<ROOMTYPE>Cinema</ROOMTYPE>
<ADDRESS>ESPAÇO GUIMARÃES - RUA 25 DE ABRIL - SILVARES</ADDRESS>
<ACTIVITY>cinema</ACTIVITY>
</FACILITIES>
<FACILITIES>
<ID>55</ID>
<NAME>CINEMAS ESPAÇO GUIMARÃES - SALA 3</NAME>
<CAPACITY>86</CAPACITY>
<ROOMTYPE>Cinema</ROOMTYPE>
<ADDRESS>ESPAÇO GUIMARÃES RUA 25 DE ABRIL  SILVARES</ADDRESS>
<ACTIVITY>cinema</ACTIVITY>
</FACILITIES>
<FACILITIES>
<ID>56</ID>
<NAME>CINEMAS ESPAÇO GUIMARÃES - SALA 4</NAME>
<CAPACITY>100</CAPACITY>
<ROOMTYPE>Cinema</ROOMTYPE>
<ADDRESS>ESPAÇO GUIMARÃES RUA 25 DE ABRIL  SILVARES</ADDRESS>
<ACTIVITY>cinema</ACTIVITY>
</FACILITIES>
<FACILITIES>
<ID>57</ID>
<NAME>CINEMAS ESPAÇO GUIMARÃES - SALA 5</NAME>
<CAPACITY>242</CAPACITY>
<ROOMTYPE>Cinema</ROOMTYPE>
<ADDRESS>ESPAÇO GUIMARÃES RUA 25 DE ABRIL  SILVARES</ADDRESS>
<ACTIVITY>cinema</ACTIVITY>
</FACILITIES>
</MUNICIPALITIES>
<MUNICIPALITIES>
<COD>309</COD>
<DESIGNATION>Póvoa de Lanhoso</DESIGNATION>
<REGION>
<COD>1</COD>
<DESIGNATION>Norte</DESIGNATION>
</REGION>
<FACILITIES>
<ID>58</ID>
<NAME>THEATRO CLUB</NAME>
<CAPACITY>120</CAPACITY>
<ROOMTYPE>Teatro</ROOMTYPE>
<ADDRESS>LARGO ANTÓNIO LOPES</ADDRESS>
<ACTIVITY>teatro</ACTIVITY>
</FACILITIES>
</MUNICIPALITIES>
<MUNICIPALITIES>
<COD>310</COD>
<DESIGNATION>Terras de Bouro</DESIGNATION>
<REGION>
<COD>1</COD>
<DESIGNATION>Norte</DESIGNATION>
</REGION>
<FACILITIES>
<ID>38</ID>
<NAME>AUDITÓRIO DO CENTRO DE ANIMAÇÃO DO GERÊS</NAME>
<CAPACITY>150</CAPACITY>
<ROOMTYPE>Auditório</ROOMTYPE>
<ADDRESS>TERRAS DE BOURO</ADDRESS>
<ACTIVITY>música</ACTIVITY>
</FACILITIES>
</MUNICIPALITIES>
<MUNICIPALITIES>
<COD>311</COD>
<DESIGNATION>Vieira do Minho</DESIGNATION>
<REGION>
<COD>1</COD>
<DESIGNATION>Norte</DESIGNATION>
</REGION>
<FACILITIES>
<ID>59</ID>
<NAME>AUDITÓRIO MUNICIPAL DE VIEIRA DO MINHO</NAME>
<CAPACITY>258</CAPACITY>
<ROOMTYPE>Auditório</ROOMTYPE>
<ADDRESS>PRAÇA DO PROFESSOR BRÁS DA MOTA</ADDRESS>
<ACTIVITY>cinema</ACTIVITY>
<ACTIVITY>dança</ACTIVITY>
<ACTIVITY>música</ACTIVITY>
<ACTIVITY>teatro</ACTIVITY>
</FACILITIES>
</MUNICIPALITIES>
<MUNICIPALITIES>
<COD>312</COD>
<DESIGNATION>Vila Nova de Famalicão</DESIGNATION>
<REGION>
<COD>1</COD>
<DESIGNATION>Norte</DESIGNATION>
</REGION>
<FACILITIES>
<ID>63</ID>
<NAME>CASA DAS ARTES - CAFÉ CONCERTO</NAME>
<CAPACITY>50</CAPACITY>
<ROOMTYPE>Café concerto</ROOMTYPE>
<ADDRESS>AV DR CARLOS BACELAR - PARQUE DE SINÇÃES</ADDRESS>
<ACTIVITY>música</ACTIVITY>
</FACILITIES>
<FACILITIES>
<ID>60</ID>
<NAME>AUDITÓRIO DO CENTRO CULTURAL DE JOANE</NAME>
<CAPACITY>204</CAPACITY>
<ROOMTYPE>Auditório</ROOMTYPE>
<ADDRESS>RUA DR. AGOSTINHO FERNANDES, 113</ADDRESS>
<ACTIVITY>cinema</ACTIVITY>
<ACTIVITY>dança</ACTIVITY>
<ACTIVITY>música</ACTIVITY>
<ACTIVITY>teatro</ACTIVITY>
</FACILITIES>
<FACILITIES>
<ID>61</ID>
<NAME>CASA DAS ARTES - GRANDE AUDITÓRIO</NAME>
<CAPACITY>494</CAPACITY>
<ROOMTYPE>Auditório</ROOMTYPE>
<ADDRESS>AV DR CARLOS BACELAR - PARQUE DE SINÇÃES</ADDRESS>
<ACTIVITY>cinema</ACTIVITY>
<ACTIVITY>dança</ACTIVITY>
<ACTIVITY>música</ACTIVITY>
</FACILITIES>
<FACILITIES>
<ID>62</ID>
<NAME>CASA DAS ARTES - PEQUENO AUDITÓRIO</NAME>
<CAPACITY>124</CAPACITY>
<ROOMTYPE>Auditório</ROOMTYPE>
<ADDRESS>AV DR CARLOS BACELAR - PARQUE DE SINÇÃES</ADDRESS>
<ACTIVITY>cinema</ACTIVITY>
<ACTIVITY>música</ACTIVITY>
</FACILITIES>
</MUNICIPALITIES>
<MUNICIPALITIES>
<COD>313</COD>
<DESIGNATION>Vila Verde</DESIGNATION>
<REGION>
<COD>1</COD>
<DESIGNATION>Norte</DESIGNATION>
</REGION>
</MUNICIPALITIES>
<MUNICIPALITIES>
<COD>314</COD>
<DESIGNATION>Vizela</DESIGNATION>
<REGION>
<COD>1</COD>
<DESIGNATION>Norte</DESIGNATION>
</REGION>
<FACILITIES>
<ID>67</ID>
<NAME>ESPAÇO MULTIUSOS AO AR LIVRE - VIZELA</NAME>
<CAPACITY>8000</CAPACITY>
<ROOMTYPE>Recinto multiusos</ROOMTYPE>
<ADDRESS>RUA DA PORTELA</ADDRESS>
<ACTIVITY>música</ACTIVITY>
</FACILITIES>
<FACILITIES>
<ID>64</ID>
<NAME>CINEMA FORUM VIZELA - SALA 1</NAME>
<CAPACITY>133</CAPACITY>
<ROOMTYPE>Cinema</ROOMTYPE>
<ADDRESS>QTA STA SUSANA - S. MIGUEL</ADDRESS>
<ACTIVITY>cinema</ACTIVITY>
</FACILITIES>
<FACILITIES>
<ID>65</ID>
<NAME>CINEMA FORUM VIZELA - SALA 2</NAME>
<CAPACITY>103</CAPACITY>
<ROOMTYPE>Cinema</ROOMTYPE>
<ADDRESS>QTA STA SUSANA - S. MIGUEL</ADDRESS>
<ACTIVITY>cinema</ACTIVITY>
</FACILITIES>
<FACILITIES>
<ID>66</ID>
<NAME>CINEMA FORUM VIZELA - SALA 3</NAME>
<CAPACITY>103</CAPACITY>
<ROOMTYPE>Cinema</ROOMTYPE>
<ADDRESS>QTA STA SUSANA - S. MIGUEL</ADDRESS>
<ACTIVITY>cinema</ACTIVITY>
</FACILITIES>
</MUNICIPALITIES>
</DISTRICT>
<DISTRICT>
<_ID>4</_ID>
<DESIGNATION>Bragança</DESIGNATION>
<REGION>
<COD>1</COD>
<DESIGNATION>Norte</DESIGNATION>
</REGION>
<MUNICIPALITIES>
<COD>409</COD>
<DESIGNATION>Torre de Moncorvo</DESIGNATION>
<REGION>
<COD>1</COD>
<DESIGNATION>Norte</DESIGNATION>
</REGION>
<FACILITIES>
<ID>242</ID>
<NAME>CINE TEATRO DE TORRE DE MONCORVO</NAME>
<CAPACITY>293</CAPACITY>
<ROOMTYPE>Cine-Teatro</ROOMTYPE>
<ADDRESS>AVENIDA ENGENHEIRO DUARTE PACHECO</ADDRESS>
<ACTIVITY>cinema</ACTIVITY>
<ACTIVITY>dança</ACTIVITY>
<ACTIVITY>música</ACTIVITY>
<ACTIVITY>teatro</ACTIVITY>
</FACILITIES>
</MUNICIPALITIES>
<MUNICIPALITIES>
<COD>401</COD>
<DESIGNATION>Alfandega da Fé</DESIGNATION>
<REGION>
<COD>1</COD>
<DESIGNATION>Norte</DESIGNATION>
</REGION>
</MUNICIPALITIES>
<MUNICIPALITIES>
<COD>402</COD>
<DESIGNATION>Bragança</DESIGNATION>
<REGION>
<COD>1</COD>
<DESIGNATION>Norte</DESIGNATION>
</REGION>
<FACILITIES>
<ID>265</ID>
<NAME>TEATRO MUNICIPAL DE BRAGANÇA</NAME>
<CAPACITY>400</CAPACITY>
<ROOMTYPE>Teatro</ROOMTYPE>
<ADDRESS>AVENIDA DR. FRANCISCO SÁ CARNEIRO</ADDRESS>
<ACTIVITY>cinema</ACTIVITY>
<ACTIVITY>dança</ACTIVITY>
<ACTIVITY>música</ACTIVITY>
<ACTIVITY>teatro</ACTIVITY>
</FACILITIES>
</MUNICIPALITIES>
<MUNICIPALITIES>
<COD>403</COD>
<DESIGNATION>Carrazeda de Ansiães</DESIGNATION>
<REGION>
<COD>1</COD>
<DESIGNATION>Norte</DESIGNATION>
</REGION>
<FACILITIES>
<ID>240</ID>
<NAME>AUDITÓRIO MUNICIPAL CENTRO INOVAÇAO TEC INOVARURAL</NAME>
<CAPACITY>213</CAPACITY>
<ROOMTYPE>Auditório</ROOMTYPE>
<ADDRESS>R LUÍS DE CAMÕES</ADDRESS>
<ACTIVITY>cinema</ACTIVITY>
<ACTIVITY>música</ACTIVITY>
<ACTIVITY>teatro</ACTIVITY>
</FACILITIES>
</MUNICIPALITIES>
<MUNICIPALITIES>
<COD>404</COD>
<DESIGNATION>Freixo Espada a Cinta</DESIGNATION>
<REGION>
<COD>1</COD>
<DESIGNATION>Norte</DESIGNATION>
</REGION>
<FACILITIES>
<ID>241</ID>
<NAME>AUDITÓRIO MUNICIPAL DE FREIXO DE ESPADA Á CINTA</NAME>
<CAPACITY>179</CAPACITY>
<ROOMTYPE>Auditório</ROOMTYPE>
<ADDRESS>AVENIDA GUERRA JUNQUEIRO</ADDRESS>
<ACTIVITY>cinema</ACTIVITY>
<ACTIVITY>dança</ACTIVITY>
<ACTIVITY>música</ACTIVITY>
<ACTIVITY>teatro</ACTIVITY>
</FACILITIES>
</MUNICIPALITIES>
<MUNICIPALITIES>
<COD>405</COD>
<DESIGNATION>Macedo de Cavaleiros</DESIGNATION>
<REGION>
<COD>1</COD>
<DESIGNATION>Norte</DESIGNATION>
</REGION>
<FACILITIES>
<ID>266</ID>
<NAME>CINE TEATRO DE MACEDO DE CAVALEIROS</NAME>
<CAPACITY>305</CAPACITY>
<ROOMTYPE>Cine-Teatro</ROOMTYPE>
<ADDRESS>RUA ENGENHEIRO MOURA PEGADO</ADDRESS>
<ACTIVITY>cinema</ACTIVITY>
<ACTIVITY>música</ACTIVITY>
<ACTIVITY>teatro</ACTIVITY>
</FACILITIES>
</MUNICIPALITIES>
<MUNICIPALITIES>
<COD>406</COD>
<DESIGNATION>Miranda do Douro</DESIGNATION>
<REGION>
<COD>1</COD>
<DESIGNATION>Norte</DESIGNATION>
</REGION>
<FACILITIES>
<ID>267</ID>
<NAME>AUDITÓRIO MUNICIPAL DE MIRANDA DO DOURO</NAME>
<CAPACITY>280</CAPACITY>
<ROOMTYPE>Auditório</ROOMTYPE>
<ADDRESS>RUA DA TRINDADE</ADDRESS>
<ACTIVITY>dança</ACTIVITY>
<ACTIVITY>música</ACTIVITY>
<ACTIVITY>teatro</ACTIVITY>
</FACILITIES>
<FACILITIES>
<ID>268</ID>
<NAME>MINI AUDITÓRIO MUNICIPAL DE MIRANDA DO DOURO</NAME>
<CAPACITY>87</CAPACITY>
<ROOMTYPE>Auditório</ROOMTYPE>
<ADDRESS>MIRANDA DO DOURO</ADDRESS>
<ACTIVITY>cinema</ACTIVITY>
<ACTIVITY>música</ACTIVITY>
<ACTIVITY>teatro</ACTIVITY>
</FACILITIES>
</MUNICIPALITIES>
<MUNICIPALITIES>
<COD>407</COD>
<DESIGNATION>Mirandela</DESIGNATION>
<REGION>
<COD>1</COD>
<DESIGNATION>Norte</DESIGNATION>
</REGION>
</MUNICIPALITIES>
<MUNICIPALITIES>
<COD>408</COD>
<DESIGNATION>Mogadouro</DESIGNATION>
<REGION>
<COD>1</COD>
<DESIGNATION>Norte</DESIGNATION>
</REGION>
<FACILITIES>
<ID>270</ID>
<NAME>AUDITÓRIO DA CASA DA CULTURA DE MOGADOURO</NAME>
<CAPACITY>199</CAPACITY>
<ROOMTYPE>Auditório</ROOMTYPE>
<ADDRESS>LARGO DAS EIRAS</ADDRESS>
<ACTIVITY>cinema</ACTIVITY>
<ACTIVITY>dança</ACTIVITY>
<ACTIVITY>música</ACTIVITY>
<ACTIVITY>teatro</ACTIVITY>
</FACILITIES>
<FACILITIES>
<ID>269</ID>
<NAME>PRAÇA DE TOIROS DE URRÓS</NAME>
<CAPACITY>3500</CAPACITY>
<ROOMTYPE>Praça de touros</ROOMTYPE>
<ADDRESS>URRÓS</ADDRESS>
<ACTIVITY>tauromaquia</ACTIVITY>
</FACILITIES>
</MUNICIPALITIES>
<MUNICIPALITIES>
<COD>410</COD>
<DESIGNATION>Vila Flor</DESIGNATION>
<REGION>
<COD>1</COD>
<DESIGNATION>Norte</DESIGNATION>
</REGION>
</MUNICIPALITIES>
<MUNICIPALITIES>
<COD>411</COD>
<DESIGNATION>Vimioso</DESIGNATION>
<REGION>
<COD>1</COD>
<DESIGNATION>Norte</DESIGNATION>
</REGION>
<FACILITIES>
<ID>271</ID>
<NAME>AUDITÓRIO DA CASA DA CULTURA DO VIMIOSO</NAME>
<CAPACITY>168</CAPACITY>
<ROOMTYPE>Auditório</ROOMTYPE>
<ADDRESS>RUA DO CANO</ADDRESS>
<ACTIVITY>cinema</ACTIVITY>
<ACTIVITY>dança</ACTIVITY>
<ACTIVITY>música</ACTIVITY>
<ACTIVITY>teatro</ACTIVITY>
</FACILITIES>
</MUNICIPALITIES>
<MUNICIPALITIES>
<COD>412</COD>
<DESIGNATION>Vinhais</DESIGNATION>
<REGION>
<COD>1</COD>
<DESIGNATION>Norte</DESIGNATION>
</REGION>
<FACILITIES>
<ID>272</ID>
<NAME>PRAÇA DE TOIROS DE VINHAIS</NAME>
<CAPACITY>1952</CAPACITY>
<ROOMTYPE>Praça de touros</ROOMTYPE>
<ADDRESS>VINHAIS</ADDRESS>
<ACTIVITY>tauromaquia</ACTIVITY>
</FACILITIES>
</MUNICIPALITIES>
</DISTRICT>
</DATA>"""

my_dict = xmltodict.parse(MY_XML_HERE, postprocessor=postprocessor, encoding='ISO-8859-1')

print(json.dumps(parse_one_item_arrays(my_dict), indent=4, ensure_ascii=False))
